# Generated by Django 5.0.6 on 2024-06-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_user_alter_comment_user_delete_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
