# Generated by Django 5.0.6 on 2024-06-23 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_posttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.tag')),
            ],
        ),
    ]
